# Generated by Django 2.2.3 on 2019-08-06 08:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190806_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=blog.models.generate_filename),
        ),
    ]
