# Generated by Django 2.2.3 on 2019-08-07 08:53

from django.db import migrations, models
import user_post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to=user_post.models.generate_filename)),
            ],
            options={
                'db_table': 'user_post',
            },
        ),
    ]
